config/routes.rb
Rails.application.routes.draw do

  resources :users
    root 'welcome#index'

    resources :video_models

    post 'details', to: 'video_models#json_data'

    get '/details/json_show', to: 'video_models#json_show'


    get 'find', to: 'video_models#find'

    post '/video_models/new', to: 'video_models#create'


  # post 'json_post', to: 'video_models#create'


  #resources :moviedata

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/video_model.rb
class VideoModel < ApplicationRecord
include HTTParty



validates :backdrop_path, :presence => true, :uniqueness => true

validates :imdb_id, :presence => true, :uniqueness => true

validates :original_language, :presence => true

validates :original_title, :presence => true, :uniqueness => true

validates :overview, :presence => true, :uniqueness => true

validates :popularity, :presence => true

validates :poster_path, :presence => true, :uniqueness => true

validates :release_date, :presence => true

validates :vote_average, :presence => true

validates :vote_count, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname)
    end
end

app/controllers/video_models_controller.rb
class VideoModelsController < ApplicationController
  #before_action :set_video_model, only: [:show, :edit, :update, :destroy]

  # GET /video_models
  # GET /video_models.json




  def index
    @video_models = VideoModel.all
    # @video_models = HTTParty.get('http://rubygems.org/api/v1/versions/httparty.json')
  end

  # GET /video_models/1
  # GET /video_models/1.json
  def show
    @video_model = VideoModel.find(params[:id])
  end

  def find
    render 'find'
  end

   def json_show
     @video_model = params[:video_model]
   end

  # GET /video_models/new
  def new
    @video_model = VideoModel.new
  end

  # GET /video_models/1/edit
  def edit
    @video_model = VideoModel.find(params[:id])
  end

  # POST /video_models
  # POST /video_models.json
  def create
    @video_model = VideoModel.new(video_model_params)


    respond_to do |format|
      if @video_model.save
        # @video_model=params[:video_model]
        format.html { redirect_to @video_model, notice: 'Video model was successfully created.' }
        format.json { render :show, status: :created, location: @video_model }
      else
        format.html { render :new }
        format.json { render json: @video_model.errors, status: :unprocessable_entity }
      end
    end
  end

  def json_data

    # puts @imdb_id.inspect
   @imdb_id = params[:imdb_id]
     # if params[:imdb_id].present?
    if @imdb_id.present?
      @video_model = HTTParty.get('https://api.themoviedb.org/3/find/' + params[:imdb_id] + '?api_key=b8df5110fb459bebc8d5cb7cbb6acfe8&language=en-US&external_source=imdb_id')
      if (@video_model['movie_results'] != [] )
        render 'json_show'
      else
        redirect_to find_path, notice: 'Enter valid Imdb ID'
        # , :video_model => @video_model
      end
    else
      redirect_to find_path, notice: 'Please Enter Imdb ID'
    end

    # end

  end

  # PATCH/PUT /video_models/1
  # PATCH/PUT /video_models/1.json
  def update

    @video_model = VideoModel.find(params[:id])
    respond_to do |format|
      if @video_model.update(video_model_params)
        format.html { redirect_to @video_model, notice: 'Video model was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_model }
      else
        format.html { render :edit }
        format.json { render json: @video_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_models/1
  # DELETE /video_models/1.json
  def destroy


    @video_model = VideoModel.find(params[:id])

    if @video_model.present?
    @video_model.destroy
    end

    respond_to do |format|
      format.html { redirect_to video_models_url, notice: 'Video model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_model
      @video_model = VideoModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_model_params
      params.require(:video_model).permit(:adult, :backdrop_path, :imdb_id, :original_language, :original_title, :overview, :popularity, :poster_path, :release_date, :video, :vote_average, :vote_count)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moviedata_helper.rb
module MoviedataHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_models_helper.rb
module VideoModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vidlib</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/moviedata/index.html.erb
<h1>Moviedata#index</h1>
<p>Find me in app/views/moviedata/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname, id: :user_fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname, id: :user_lname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/video_models/_form.html.erb
<%= form_with(model: video_model, local: true) do |form| %>
  <% if @video_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video_model.errors.count, "error") %> prohibited this video_model from being saved:</h2>

      <ul>
      <% @video_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :imdb_id %>
      <%= form.text_field :imdb_id, id: :video_model_imdb_id %>
    </div>


    <div class="field">
    <%= form.label :adult %>
    <%= form.check_box :adult, id: :video_model_adult %>
  </div>

  <div class="field">
    <%= form.label :backdrop_path %>
    <%= form.text_field :backdrop_path, id: :video_model_backdrop_path %>
  </div>


  <div class="field">
    <%= form.label :original_language %>
    <%= form.text_field :original_language, id: :video_model_original_language %>
  </div>

  <div class="field">
    <%= form.label :original_title %>
    <%= form.text_field :original_title, id: :video_model_original_title %>
  </div>

  <div class="field">
    <%= form.label :overview %>
    <%= form.text_field :overview, id: :video_model_overview %>
  </div>

  <div class="field">
    <%= form.label :popularity %>
    <%= form.text_field :popularity, id: :video_model_popularity %>
  </div>

  <div class="field">
    <%= form.label :poster_path %>
    <%= form.text_field :poster_path, id: :video_model_poster_path %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.text_field :release_date, id: :video_model_release_date %>
  </div>


  <div class="field">
    <%= form.label :video %>
    <%= form.check_box :video, id: :video_model_video %>
  </div>

  <div class="field">
    <%= form.label :vote_average %>
    <%= form.text_field :vote_average, id: :video_model_vote_average %>
  </div>

  <div class="field">
    <%= form.label :vote_count %>
    <%= form.number_field :vote_count, id: :video_model_vote_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<!---
<
<script type="text/javascript" charset="utf-8">
    $("#fetch").on('click', function(){
        var value1 = $('#video_model_imdb_id').val();


        console.log(value1);
       console.log('--------------------------------------');

        $.ajax({
            url: "",
            data: {
                id: value1
            },
            dataType: "json"
        })
    })
</script>>    ->

app/views/video_models/edit.html.erb
<h1>Editing Video Model</h1>

<%= render 'form', video_model: @video_model %>

<%= link_to 'Show', @video_model %> |
<%= link_to 'Back', video_models_path %>

app/views/video_models/find.html.erb
<label> Imdb ID</label>
<%= form_tag details_path , id:"imdb_form" do %>
    <%= text_field_tag  :imdb_id %>
    <p id="demo">fill imdb id</p>
    <%= submit_tag 'Fetch Movie Details', id: 'ftch-mv-btn', class: 'submit' %>
<% end %>


<script>
    $('#demo').hide();
    $('#ftch-mv-btn').on('click', function myFunction(event) {
        var inpObj = $("#imdb_id");
        if (inpObj.val() == "") {
            $('#demo').show();
            event.preventDefault();
        }
    });




    //    $('#demo').hide();
//    $('#ftch-mv-btn').on('click', function(event) {
//        var text = $('#ftch-mv-btn').html();
//        if (text == "" ){
//            $('#demo').show();
//               event.preventDefault();
//        }
//    });
</script>

<style>
  #demo{
  color: red;
  }


</style>

app/views/video_models/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New article', new_video_model_path %>
<h1>Video Models</h1>
<table class="table">
  <thead>
    <tr>
      <th>Adult</th>
      <th>Backdrop path</th>
      <th>Imdb</th>
      <th>Original language</th>
      <th>Original title</th>
      <th>Overview</th>
      <th>Popularity</th>
      <th>Poster path</th>
      <th>Release date</th>
      <th>Video</th>
      <th>Vote average</th>
      <th>Vote count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_models.each do |video_model| %>

      <tr>
        <td><%= video_model.adult %></td>
        <td><%= video_model.backdrop_path %></td>
        <td><%= video_model.imdb_id %></td>
        <td><%= video_model.original_language %></td>
        <td><%= video_model.original_title %></td>
        <td><%= video_model.overview %></td>
        <td><%= video_model.popularity %></td>
        <td><%= video_model.poster_path %></td>
        <td><%= video_model.release_date %></td>
        <td><%= video_model.video %></td>
        <td><%= video_model.vote_average %></td>
        <td><%= video_model.vote_count %></td>
        <td class="btn"><%= link_to 'Show', video_model %></td>
        <td class="btn"><%= link_to 'Edit', edit_video_model_path(video_model) %></td>
        <td class="btn"><%= link_to 'Destroy', video_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>

    <% end %>

  </tbody>

</table>




<br>

<%= link_to 'Find Video', find_path, method: :get %>
<%= link_to 'Back to homepage', root_path , method: :get %>
<%#= link_to 'sdzfbfind Video', details_json_show_path , method: :get %>
<%#= link_to 'new video', new_video_model_path, method: :get %>

app/views/video_models/json_show.html.erb
<!--<#%= fields_for :video_model do |p| %>-->
    <!--Admin?: <#%= p.text_field :imdb_id %>-->
<!--<#% end %>-->
<%#= @video_model.inspect %>
<%#= @video_model['movie_results']['backdrop_path'] %>


<!--<%#= @video_model.each do |a| %>-->
<!--<%#= Console.log(a.backdrop)%>-->


<!--<%#end%>-->

<% imdb_id = @imdb_id  %>

<% backdrop_path = @video_model['movie_results'][0]['backdrop_path'] %>

<% adult= @video_model['movie_results'][0]['adult'] %>

<% original_language= @video_model['movie_results'][0]['original_language'] %>

<% original_title= @video_model['movie_results'][0]['original_title'] %>

<% overview= @video_model['movie_results'][0]['overview'] %>

<% popularity= @video_model['movie_results'][0]['popularity'] %>

<% poster_path= @video_model['movie_results'][0]['poster_path'] %>

<% release_date= @video_model['movie_results'][0]['release_date'] %>

<% movie_id= @video_model['movie_results'][0]['id'] %>

<% title= @video_model['movie_results'][0]['title'] %>

<% video= @video_model['movie_results'][0]['video'] %>

<% vote_average= @video_model['movie_results'][0]['vote_average'] %>

<% vote_count= @video_model['movie_results'][0]['vote_count'] %>


<%= form_for :video_model ,:url => "/video_models", :html => {:method => :post} do |f| %>


    <div>
      <%= f.label :imdb_id %>
      <%= f.text_field :imdb_id, :value => imdb_id %>
    </div>

    <br>
    <br>

    <div>
      <%= f.label :adult %>
   <%= f.check_box :adult, :checked => adult %>
    </div>

    <br>
    <br>

    <div>
      <%= f.label :backdrop_path %>
    <%= f.text_field :backdrop_path, :value => backdrop_path %>
    </div>

    <br>
    <br>

    <div>
      <%= f.label :original_language %>
      <%= f.text_field :original_language, :value => original_language %>
    </div>

    <br><br>

    <div>
      <%= f.label :title%>
      <%= f.text_field :title, :value => title %>
    </div>

    <br><br>

    <div>
      <%= f.label :original_title %>
      <%= f.text_field :original_title, :value => original_title %>
    </div>

    <br><br>

    <div>
      <%= f.label :overview %>
      <%= f.text_area :overview, :value => overview %>
    </div>

      <br><br>

    <div>
      <%= f.label :popularity %>
      <%= f.number_field :popularity, :value => popularity %>
    </div>

    <br><br>

    <div>
      <%= f.label :poster_path %>
      <%= f.text_field :poster_path, :value => poster_path %>
    </div>

      <br><br>

    <div>
      <%= f.label :release_date %>
      <%= f.text_field :release_date, :value => release_date %>
    </div>

      <br><br>


    <div>
      <%= f.label :movie_id %>
    <%= f.number_field :movie_id, :value => movie_id %>
    </div>

      <br><br>

    <div>
      <%= f.label :video %>
       <%= f.check_box :video, :checked => video %>
    </div>

      <br><br>

    <div>
      <%= f.label :vote_average %>
    <%= f.number_field :vote_average, :value => vote_average %>
    </div>

     <br><br>

    <div>
      <%= f.label :vote_count %>
      <%= f.number_field :vote_count, :value => vote_count %>
    </div>

    <br><br>

    <div>
      <%= f.submit %>
    </div>




<% end %>

app/views/video_models/new.html.erb
<h1>New Video Model</h1>

<%= render 'form', video_model: @video_model %>

<%= link_to 'Back', video_models_path %>

app/views/video_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adult:</strong>
  <%= @video_model.adult %>
</p>

<p>
  <strong>Backdrop path:</strong>
  <%= @video_model.backdrop_path %>
</p>


<p>
  <strong>Id:</strong>
  <%= @video_model.id %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @video_model.imdb_id %>
</p>

<p>
  <strong>Original language:</strong>
  <%= @video_model.original_language %>
</p>

<p>
  <strong>Original title:</strong>
  <%= @video_model.original_title %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @video_model.overview %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @video_model.popularity %>
</p>

<p>
  <strong>Poster path:</strong>
  <%= @video_model.poster_path %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @video_model.release_date %>
</p>



<p>
  <strong>Video:</strong>
  <%= @video_model.video %>
</p>

<p>
  <strong>Vote average:</strong>
  <%= @video_model.vote_average %>
</p>

<p>
  <strong>Vote count:</strong>
  <%= @video_model.vote_count %>
</p>

<%= link_to 'Edit', edit_video_model_path(@video_model)  %> |
<%= link_to 'Back', video_models_path %>

app/views/welcome/index.html.erb
<big><marquee> <h1>hello , Video Library !</h1> </marquee></big>

<%= link_to 'Video Library Index' , controller: 'video_models'%>